import type { AssetDetail } from "@/features/assets/types"

/** Canonical synthetic Assets. Relationships use stable fixture IDs. */
export const assetFixtures: AssetDetail[] = [
  {
    id: 1,
    companyId: 1,
    siteId: 1,
    contactId: null,
    name: "Office VPN gateway",
    assetType: "network_device",
    status: "active",
    manufacturer: "NetCore",
    model: "Secure Gateway 60",
    serialNumber: "DEMO-NS-0001",
    assetTag: "NS-IT-001",
    hostname: "NS-RAL-FW-01",
    operatingSystem: "NetCore OS",
  },
  {
    id: 2,
    companyId: 2,
    siteId: 2,
    contactId: null,
    name: "Reception workstation",
    assetType: "desktop",
    status: "active",
    manufacturer: "Aster Computing",
    model: "Office Desktop 500",
    serialNumber: "DEMO-JD-0002",
    assetTag: "JD-PC-002",
    hostname: "JD-RECEPTION-01",
    operatingSystem: "Windows 11 Pro",
  },
  {
    id: 3,
    companyId: 3,
    siteId: 3,
    contactId: null,
    name: "Shipping label printer",
    assetType: "printer",
    status: "maintenance",
    manufacturer: "Meridian Print",
    model: "Label 420",
    serialNumber: "DEMO-CS-0003",
    assetTag: "CS-PR-003",
    hostname: "CS-LABEL-02",
    operatingSystem: null,
  },
  {
    id: 4,
    companyId: 5,
    siteId: 4,
    contactId: null,
    name: "Application server",
    assetType: "server",
    status: "active",
    manufacturer: "Aster Computing",
    model: "Rack Server 800",
    serialNumber: "DEMO-HL-0004",
    assetTag: "HL-SV-004",
    hostname: "APP-SRV-02",
    operatingSystem: "Ubuntu Server",
  },
  {
    id: 5,
    companyId: 3,
    siteId: null,
    contactId: 7,
    name: "Replacement mobile phone",
    assetType: "mobile_device",
    status: "active",
    manufacturer: "Aster Mobile",
    model: "Handset 12",
    serialNumber: "DEMO-CS-0005",
    assetTag: "CS-MB-005",
    hostname: null,
    operatingSystem: "Android",
  },
  {
    id: 6,
    companyId: 2,
    siteId: 5,
    contactId: null,
    name: "Branch resolver",
    assetType: "network_device",
    status: "active",
    manufacturer: "NetCore",
    model: "Resolver 200",
    serialNumber: "DEMO-JD-0006",
    assetTag: "JD-NW-006",
    hostname: "JD-BR-DNS-01",
    operatingSystem: "NetCore OS",
  },
  {
    id: 7,
    companyId: 1,
    siteId: null,
    contactId: null,
    name: "Spare laptop",
    assetType: "laptop",
    status: "in_stock",
    manufacturer: "Aster Computing",
    model: "Travel Laptop 14",
    serialNumber: "DEMO-NS-0007",
    assetTag: "NS-LT-007",
    hostname: null,
    operatingSystem: null,
  },
  {
    id: 8,
    companyId: 1,
    siteId: 6,
    contactId: null,
    name: "Studio rendering workstation",
    assetType: "desktop",
    status: "active",
    manufacturer: "Aster Computing",
    model: "Render Workstation 900",
    serialNumber: "DEMO-NS-0008",
    assetTag: "NS-WS-008",
    hostname: "NS-DUR-RENDER-01",
    operatingSystem: "Windows 11 Pro",
  },
]
