[project]
name = "mock-psa-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jacob Turpin", email = "jacobeturpin@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "psycopg[binary]>=3.2,<4",
    "pwdlib[argon2]>=0.3,<1",
    "pydantic>=2.13.5",
    "pydantic-settings>=2.10,<3",
    "pyjwt>=2.10,<3",
    "sqlmodel>=0.0.31,<0.1",
]

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[tool.fastapi]
entrypoint = "mock_psa_api.main:app"

[dependency-groups]
dev = [
    "pytest>=8.4,<9",
    "ruff>=0.13,<1",
]
