import type { SiteDetail } from "@/features/sites/types"

/** Stable synthetic site identities. Company and ticket fixtures reference these IDs. */
export const siteFixtures: SiteDetail[] = [
  {
    id: 1,
    companyId: 1,
    name: "Raleigh office",
    addressLine1: "120 Example Avenue",
    addressLine2: null,
    city: "Raleigh",
    stateProvince: "NC",
    postalCode: null,
    countryCode: "US",
    phone: "(919) 555-0101",
    timezone: "America/New_York",
  },
  {
    id: 2,
    companyId: 2,
    name: "Main practice",
    addressLine1: null,
    addressLine2: null,
    city: null,
    stateProvince: null,
    postalCode: null,
    countryCode: null,
    phone: "(919) 555-0102",
    timezone: "America/New_York",
  },
  {
    id: 3,
    companyId: 3,
    name: "Distribution warehouse",
    addressLine1: "40 Demo Lane",
    addressLine2: null,
    city: "Raleigh",
    stateProvince: "NC",
    postalCode: null,
    countryCode: "US",
    phone: null,
    timezone: "America/New_York",
  },
  {
    id: 4,
    companyId: 5,
    name: "Head office",
    addressLine1: null,
    addressLine2: null,
    city: null,
    stateProvince: null,
    postalCode: null,
    countryCode: null,
    phone: null,
    timezone: "America/New_York",
  },
  {
    id: 5,
    companyId: 2,
    name: "Branch practice",
    addressLine1: null,
    addressLine2: null,
    city: null,
    stateProvince: null,
    postalCode: null,
    countryCode: null,
    phone: null,
    timezone: null,
  },
  {
    id: 6,
    companyId: 1,
    name: "Durham studio",
    addressLine1: "88 Sample Street",
    addressLine2: "Suite 200",
    city: "Durham",
    stateProvince: "NC",
    postalCode: "27701",
    countryCode: "US",
    phone: null,
    timezone: "America/New_York",
  },
]
