import type { KnowledgeArticle } from "@/features/knowledge-articles/types"

/** Canonical, entirely synthetic articles. A record has at most one target. */
export const knowledgeArticleFixtures: KnowledgeArticle[] = [
  {
    id: 1,
    companyId: null,
    siteId: null,
    contactId: null,
    assetId: null,
    title: "First-response troubleshooting checklist",
    body: "Confirm who is affected, when the issue began, and whether work is blocked. Record the exact error text—including characters such as < and >—before changing settings.\n\nCheck for a known incident, capture a reproducible example, and note any safe workaround. Escalate when the impact grows or the initial checks do not isolate the cause.\n\nKeep customer updates factual. Do not imply that a fix has been applied until it is verified.",
    createdAt: "2026-09-08T13:00:00Z",
    updatedAt: "2026-09-15T09:00:00Z",
  },
  {
    id: 2,
    companyId: 1,
    siteId: null,
    contactId: null,
    assetId: null,
    title: "Northstar remote access handoff",
    body: "For Northstar Architecture remote-access cases, capture the affected team, office, approximate start time, and whether file transfers are interrupted.\n\nCoordinate a supervised test window with the customer contact. Record gateway observations in the ticket before proposing a configuration change.",
    createdAt: "2026-09-10T15:30:00Z",
    updatedAt: "2026-09-15T13:45:00Z",
  },
  {
    id: 3,
    companyId: null,
    siteId: 5,
    contactId: null,
    assetId: null,
    title: "Branch practice DNS verification",
    body: "At Branch practice, compare internal and external lookups from two workstations. Record the resolver in use and repeat the checks after any approved network change.\n\nIf name resolution is intermittent, capture the failed name and time of the attempt before escalating.",
    createdAt: "2026-09-12T10:15:00Z",
    updatedAt: "2026-09-14T17:10:00Z",
  },
  {
    id: 4,
    companyId: null,
    siteId: null,
    contactId: 7,
    assetId: null,
    title: "Replacement mobile device enrollment",
    body: "Coordinate enrollment of Robin Carter's replacement device with the contact. Verify management registration, compliance, and access to company email.\n\nConfirm the prior device is retired in the customer inventory before closing the related ticket.",
    createdAt: "2026-09-12T14:00:00Z",
    updatedAt: "2026-09-14T15:20:00Z",
  },
  {
    id: 5,
    companyId: null,
    siteId: null,
    contactId: null,
    assetId: 1,
    title: "Office VPN gateway session diagnostics",
    body: "Review the Office VPN gateway's session and tunnel renegotiation logs for the affected window. Compare the current timeout settings with the last known-good configuration.\n\nRun a supervised reconnect and file-transfer test. Document the observations and obtain approval before applying any change.",
    createdAt: "2026-09-15T12:10:00Z",
    updatedAt: "2026-09-15T14:05:00Z",
  },
  {
    id: 6,
    companyId: 3,
    siteId: null,
    contactId: null,
    assetId: null,
    title: "Warehouse label printer escalation",
    body: "For Crescent Supply Co. label-printer incidents, confirm the printer's power and network indicators and capture the queue state.\n\nIf the device remains offline, ask the warehouse contact for a photo of the indicators and record the result in the ticket. Avoid clearing the queue until the pending labels are accounted for.",
    createdAt: "2026-09-11T08:20:00Z",
    updatedAt: "2026-09-15T12:40:00Z",
  },
]
