import type { TicketSummary } from "@/features/tickets/types"

/** Synthetic records used only to establish the frontend UX. */
export const ticketFixtures: TicketSummary[] = [
  {
    id: 1048,
    summary: "VPN disconnecting across Raleigh office",
    companyId: 1,
    company: "Northstar Architecture",
    contact: "Morgan Lee",
    priority: "urgent",
    status: "in_progress",
    assignee: "Alex Technician",
    source: "phone",
    updatedAt: "2 min ago",
  },
  {
    id: 1047,
    summary: "Outlook sign-in loops after MFA prompt",
    companyId: 2,
    company: "Juniper Dental Group",
    contact: "Priya Shah",
    priority: "high",
    status: "open",
    assignee: "Sam Rivera",
    source: "email",
    updatedAt: "11 min ago",
  },
  {
    id: 1046,
    summary: "Warehouse label printer reports offline",
    companyId: 3,
    company: "Crescent Supply Co.",
    contact: "Derek Wilson",
    priority: "normal",
    status: "waiting_customer",
    assignee: "Alex Technician",
    source: "portal",
    updatedAt: "28 min ago",
  },
  {
    id: 1045,
    summary: "Provision laptop for new finance hire",
    companyId: 4,
    company: "Beacon Financial Partners",
    contact: "Elena Torres",
    priority: "low",
    status: "new",
    assignee: null,
    source: "portal",
    updatedAt: "43 min ago",
  },
  {
    id: 1044,
    summary: "Nightly backup missed on APP-SRV-02",
    companyId: 5,
    company: "Hawthorne Legal",
    contact: "Chris Nguyen",
    priority: "high",
    status: "resolved",
    assignee: "Taylor Brooks",
    source: "monitoring",
    updatedAt: "1 hr ago",
  },
  {
    id: 1043,
    summary: "Microsoft 365 mail delivery delayed",
    companyId: 1,
    company: "Northstar Architecture",
    contact: "Jamie Patel",
    priority: "high",
    status: "open",
    assignee: "Sam Rivera",
    source: "phone",
    updatedAt: "2 hrs ago",
  },
  {
    id: 1042,
    summary: "Enroll replacement phone in device management",
    companyId: 3,
    company: "Crescent Supply Co.",
    contact: "Robin Carter",
    priority: "low",
    status: "closed",
    assignee: "Taylor Brooks",
    source: "email",
    updatedAt: "Yesterday",
  },
  {
    id: 1041,
    summary: "Intermittent DNS failures at branch office",
    companyId: 2,
    company: "Juniper Dental Group",
    contact: "Priya Shah",
    priority: "urgent",
    status: "resolved",
    assignee: "Alex Technician",
    source: "monitoring",
    updatedAt: "Yesterday",
  },
]
