import type { ContactDetail } from "@/features/contacts/types"

/** Canonical synthetic contacts. Ticket, company, and site views reference these IDs. */
export const contactFixtures: ContactDetail[] = [
  {
    id: 1,
    companyId: 1,
    siteId: 1,
    firstName: "Morgan",
    lastName: "Lee",
    email: "morgan.lee@northstar.example",
    phone: "(919) 555-0148",
    mobilePhone: "(919) 555-0248",
    jobTitle: "Design operations manager",
  },
  {
    id: 2,
    companyId: 2,
    siteId: 2,
    firstName: "Priya",
    lastName: "Shah",
    email: "priya.shah@juniper.example",
    phone: "(919) 555-0147",
    mobilePhone: null,
    jobTitle: "Practice manager",
  },
  {
    id: 3,
    companyId: 3,
    siteId: 3,
    firstName: "Derek",
    lastName: "Wilson",
    email: "derek.wilson@crescent.example",
    phone: "(919) 555-0146",
    mobilePhone: null,
    jobTitle: "Shipping supervisor",
  },
  {
    id: 4,
    companyId: 4,
    siteId: null,
    firstName: "Elena",
    lastName: "Torres",
    email: "elena.torres@beacon.example",
    phone: null,
    mobilePhone: null,
    jobTitle: "Finance manager",
  },
  {
    id: 5,
    companyId: 5,
    siteId: 4,
    firstName: "Chris",
    lastName: "Nguyen",
    email: "chris.nguyen@hawthorne.example",
    phone: "(919) 555-0144",
    mobilePhone: "(919) 555-0244",
    jobTitle: "IT coordinator",
  },
  {
    id: 6,
    companyId: 1,
    siteId: null,
    firstName: "Jamie",
    lastName: "Patel",
    email: "jamie.patel@northstar.example",
    phone: "(919) 555-0143",
    mobilePhone: null,
    jobTitle: "Office administrator",
  },
  {
    id: 7,
    companyId: 3,
    siteId: null,
    firstName: "Robin",
    lastName: "Carter",
    email: "robin.carter@crescent.example",
    phone: null,
    mobilePhone: null,
    jobTitle: null,
  },
  {
    id: 8,
    companyId: 1,
    siteId: 6,
    firstName: "Dana",
    lastName: "Ellis",
    email: "dana.ellis@northstar.example",
    phone: null,
    mobilePhone: null,
    jobTitle: "Studio manager",
  },
]

export function getContactName(contact: ContactDetail): string {
  return `${contact.firstName} ${contact.lastName}`
}
